// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.0
// source: fixtures.proto

package protos

import (
	loggingpb "cloud.google.com/go/logging/apiv2/loggingpb"
	monitoringpb "cloud.google.com/go/monitoring/apiv3/v2/monitoringpb"
	tracepb "cloud.google.com/go/trace/apiv2/tracepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricExpectFixture struct {
	state                           protoimpl.MessageState                        `protogen:"open.v1"`
	CreateTimeSeriesRequests        []*monitoringpb.CreateTimeSeriesRequest       `protobuf:"bytes,1,rep,name=create_time_series_requests,json=createTimeSeriesRequests,proto3" json:"create_time_series_requests,omitempty"`
	CreateMetricDescriptorRequests  []*monitoringpb.CreateMetricDescriptorRequest `protobuf:"bytes,2,rep,name=create_metric_descriptor_requests,json=createMetricDescriptorRequests,proto3" json:"create_metric_descriptor_requests,omitempty"`
	CreateServiceTimeSeriesRequests []*monitoringpb.CreateTimeSeriesRequest       `protobuf:"bytes,3,rep,name=create_service_time_series_requests,json=createServiceTimeSeriesRequests,proto3" json:"create_service_time_series_requests,omitempty"`
	SelfObservabilityMetrics        *SelfObservabilityMetric                      `protobuf:"bytes,4,opt,name=self_observability_metrics,json=selfObservabilityMetrics,proto3" json:"self_observability_metrics,omitempty"`
	UserAgent                       string                                        `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *MetricExpectFixture) Reset() {
	*x = MetricExpectFixture{}
	mi := &file_fixtures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricExpectFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricExpectFixture) ProtoMessage() {}

func (x *MetricExpectFixture) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricExpectFixture.ProtoReflect.Descriptor instead.
func (*MetricExpectFixture) Descriptor() ([]byte, []int) {
	return file_fixtures_proto_rawDescGZIP(), []int{0}
}

func (x *MetricExpectFixture) GetCreateTimeSeriesRequests() []*monitoringpb.CreateTimeSeriesRequest {
	if x != nil {
		return x.CreateTimeSeriesRequests
	}
	return nil
}

func (x *MetricExpectFixture) GetCreateMetricDescriptorRequests() []*monitoringpb.CreateMetricDescriptorRequest {
	if x != nil {
		return x.CreateMetricDescriptorRequests
	}
	return nil
}

func (x *MetricExpectFixture) GetCreateServiceTimeSeriesRequests() []*monitoringpb.CreateTimeSeriesRequest {
	if x != nil {
		return x.CreateServiceTimeSeriesRequests
	}
	return nil
}

func (x *MetricExpectFixture) GetSelfObservabilityMetrics() *SelfObservabilityMetric {
	if x != nil {
		return x.SelfObservabilityMetrics
	}
	return nil
}

func (x *MetricExpectFixture) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type SelfObservabilityMetric struct {
	state                          protoimpl.MessageState                        `protogen:"open.v1"`
	CreateTimeSeriesRequests       []*monitoringpb.CreateTimeSeriesRequest       `protobuf:"bytes,1,rep,name=create_time_series_requests,json=createTimeSeriesRequests,proto3" json:"create_time_series_requests,omitempty"`
	CreateMetricDescriptorRequests []*monitoringpb.CreateMetricDescriptorRequest `protobuf:"bytes,2,rep,name=create_metric_descriptor_requests,json=createMetricDescriptorRequests,proto3" json:"create_metric_descriptor_requests,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *SelfObservabilityMetric) Reset() {
	*x = SelfObservabilityMetric{}
	mi := &file_fixtures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfObservabilityMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfObservabilityMetric) ProtoMessage() {}

func (x *SelfObservabilityMetric) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfObservabilityMetric.ProtoReflect.Descriptor instead.
func (*SelfObservabilityMetric) Descriptor() ([]byte, []int) {
	return file_fixtures_proto_rawDescGZIP(), []int{1}
}

func (x *SelfObservabilityMetric) GetCreateTimeSeriesRequests() []*monitoringpb.CreateTimeSeriesRequest {
	if x != nil {
		return x.CreateTimeSeriesRequests
	}
	return nil
}

func (x *SelfObservabilityMetric) GetCreateMetricDescriptorRequests() []*monitoringpb.CreateMetricDescriptorRequest {
	if x != nil {
		return x.CreateMetricDescriptorRequests
	}
	return nil
}

type LogExpectFixture struct {
	state                    protoimpl.MessageState              `protogen:"open.v1"`
	WriteLogEntriesRequests  []*loggingpb.WriteLogEntriesRequest `protobuf:"bytes,1,rep,name=write_log_entries_requests,json=writeLogEntriesRequests,proto3" json:"write_log_entries_requests,omitempty"`
	UserAgent                string                              `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	SelfObservabilityMetrics *SelfObservabilityMetric            `protobuf:"bytes,3,opt,name=self_observability_metrics,json=selfObservabilityMetrics,proto3" json:"self_observability_metrics,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LogExpectFixture) Reset() {
	*x = LogExpectFixture{}
	mi := &file_fixtures_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogExpectFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogExpectFixture) ProtoMessage() {}

func (x *LogExpectFixture) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogExpectFixture.ProtoReflect.Descriptor instead.
func (*LogExpectFixture) Descriptor() ([]byte, []int) {
	return file_fixtures_proto_rawDescGZIP(), []int{2}
}

func (x *LogExpectFixture) GetWriteLogEntriesRequests() []*loggingpb.WriteLogEntriesRequest {
	if x != nil {
		return x.WriteLogEntriesRequests
	}
	return nil
}

func (x *LogExpectFixture) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LogExpectFixture) GetSelfObservabilityMetrics() *SelfObservabilityMetric {
	if x != nil {
		return x.SelfObservabilityMetrics
	}
	return nil
}

type TraceExpectFixture struct {
	state                    protoimpl.MessageState            `protogen:"open.v1"`
	BatchWriteSpansRequest   []*tracepb.BatchWriteSpansRequest `protobuf:"bytes,1,rep,name=batch_write_spans_request,json=batchWriteSpansRequest,proto3" json:"batch_write_spans_request,omitempty"`
	UserAgent                string                            `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	SelfObservabilityMetrics *SelfObservabilityMetric          `protobuf:"bytes,3,opt,name=self_observability_metrics,json=selfObservabilityMetrics,proto3" json:"self_observability_metrics,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TraceExpectFixture) Reset() {
	*x = TraceExpectFixture{}
	mi := &file_fixtures_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceExpectFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceExpectFixture) ProtoMessage() {}

func (x *TraceExpectFixture) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceExpectFixture.ProtoReflect.Descriptor instead.
func (*TraceExpectFixture) Descriptor() ([]byte, []int) {
	return file_fixtures_proto_rawDescGZIP(), []int{3}
}

func (x *TraceExpectFixture) GetBatchWriteSpansRequest() []*tracepb.BatchWriteSpansRequest {
	if x != nil {
		return x.BatchWriteSpansRequest
	}
	return nil
}

func (x *TraceExpectFixture) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *TraceExpectFixture) GetSelfObservabilityMetrics() *SelfObservabilityMetric {
	if x != nil {
		return x.SelfObservabilityMetrics
	}
	return nil
}

var File_fixtures_proto protoreflect.FileDescriptor

const file_fixtures_proto_rawDesc = "" +
	"\n" +
	"\x0efixtures.proto\x12\bfixtures\x1a\x14metric_service.proto\x1a\x15logging_service.proto\x1a\x15tracing_service.proto\"\x80\x04\n" +
	"\x13MetricExpectFixture\x12l\n" +
	"\x1bcreate_time_series_requests\x18\x01 \x03(\v2-.google.monitoring.v3.CreateTimeSeriesRequestR\x18createTimeSeriesRequests\x12~\n" +
	"!create_metric_descriptor_requests\x18\x02 \x03(\v23.google.monitoring.v3.CreateMetricDescriptorRequestR\x1ecreateMetricDescriptorRequests\x12{\n" +
	"#create_service_time_series_requests\x18\x03 \x03(\v2-.google.monitoring.v3.CreateTimeSeriesRequestR\x1fcreateServiceTimeSeriesRequests\x12_\n" +
	"\x1aself_observability_metrics\x18\x04 \x01(\v2!.fixtures.SelfObservabilityMetricR\x18selfObservabilityMetrics\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\"\x87\x02\n" +
	"\x17SelfObservabilityMetric\x12l\n" +
	"\x1bcreate_time_series_requests\x18\x01 \x03(\v2-.google.monitoring.v3.CreateTimeSeriesRequestR\x18createTimeSeriesRequests\x12~\n" +
	"!create_metric_descriptor_requests\x18\x02 \x03(\v23.google.monitoring.v3.CreateMetricDescriptorRequestR\x1ecreateMetricDescriptorRequests\"\xfa\x01\n" +
	"\x10LogExpectFixture\x12f\n" +
	"\x1awrite_log_entries_requests\x18\x01 \x03(\v2).google.logging.v2.WriteLogEntriesRequestR\x17writeLogEntriesRequests\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12_\n" +
	"\x1aself_observability_metrics\x18\x03 \x01(\v2!.fixtures.SelfObservabilityMetricR\x18selfObservabilityMetrics\"\xfa\x01\n" +
	"\x12TraceExpectFixture\x12d\n" +
	"\x19batch_write_spans_request\x18\x01 \x03(\v2).google.tracing.v2.BatchWriteSpansRequestR\x16batchWriteSpansRequest\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12_\n" +
	"\x1aself_observability_metrics\x18\x03 \x01(\v2!.fixtures.SelfObservabilityMetricR\x18selfObservabilityMetricsBfZdgithub.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector/integrationtest/protosb\x06proto3"

var (
	file_fixtures_proto_rawDescOnce sync.Once
	file_fixtures_proto_rawDescData []byte
)

func file_fixtures_proto_rawDescGZIP() []byte {
	file_fixtures_proto_rawDescOnce.Do(func() {
		file_fixtures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fixtures_proto_rawDesc), len(file_fixtures_proto_rawDesc)))
	})
	return file_fixtures_proto_rawDescData
}

var file_fixtures_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fixtures_proto_goTypes = []any{
	(*MetricExpectFixture)(nil),                        // 0: fixtures.MetricExpectFixture
	(*SelfObservabilityMetric)(nil),                    // 1: fixtures.SelfObservabilityMetric
	(*LogExpectFixture)(nil),                           // 2: fixtures.LogExpectFixture
	(*TraceExpectFixture)(nil),                         // 3: fixtures.TraceExpectFixture
	(*monitoringpb.CreateTimeSeriesRequest)(nil),       // 4: google.monitoring.v3.CreateTimeSeriesRequest
	(*monitoringpb.CreateMetricDescriptorRequest)(nil), // 5: google.monitoring.v3.CreateMetricDescriptorRequest
	(*loggingpb.WriteLogEntriesRequest)(nil),           // 6: google.logging.v2.WriteLogEntriesRequest
	(*tracepb.BatchWriteSpansRequest)(nil),             // 7: google.tracing.v2.BatchWriteSpansRequest
}
var file_fixtures_proto_depIdxs = []int32{
	4,  // 0: fixtures.MetricExpectFixture.create_time_series_requests:type_name -> google.monitoring.v3.CreateTimeSeriesRequest
	5,  // 1: fixtures.MetricExpectFixture.create_metric_descriptor_requests:type_name -> google.monitoring.v3.CreateMetricDescriptorRequest
	4,  // 2: fixtures.MetricExpectFixture.create_service_time_series_requests:type_name -> google.monitoring.v3.CreateTimeSeriesRequest
	1,  // 3: fixtures.MetricExpectFixture.self_observability_metrics:type_name -> fixtures.SelfObservabilityMetric
	4,  // 4: fixtures.SelfObservabilityMetric.create_time_series_requests:type_name -> google.monitoring.v3.CreateTimeSeriesRequest
	5,  // 5: fixtures.SelfObservabilityMetric.create_metric_descriptor_requests:type_name -> google.monitoring.v3.CreateMetricDescriptorRequest
	6,  // 6: fixtures.LogExpectFixture.write_log_entries_requests:type_name -> google.logging.v2.WriteLogEntriesRequest
	1,  // 7: fixtures.LogExpectFixture.self_observability_metrics:type_name -> fixtures.SelfObservabilityMetric
	7,  // 8: fixtures.TraceExpectFixture.batch_write_spans_request:type_name -> google.tracing.v2.BatchWriteSpansRequest
	1,  // 9: fixtures.TraceExpectFixture.self_observability_metrics:type_name -> fixtures.SelfObservabilityMetric
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_fixtures_proto_init() }
func file_fixtures_proto_init() {
	if File_fixtures_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fixtures_proto_rawDesc), len(file_fixtures_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fixtures_proto_goTypes,
		DependencyIndexes: file_fixtures_proto_depIdxs,
		MessageInfos:      file_fixtures_proto_msgTypes,
	}.Build()
	File_fixtures_proto = out.File
	file_fixtures_proto_goTypes = nil
	file_fixtures_proto_depIdxs = nil
}
